[versions]
activity = "1.8.2"
appcompat = "1.6.1"
camera-core = "1.3.0"
camera-camera2 = "1.3.0"
camera-lifecycle = "1.3.0"
camera-view = "1.3.0"
constraintlayout = "2.1.4"
core-ktx = "1.13.1"
lifecycle-runtime-ktx = "2.7.0"
lifecycle-viewmodel-ktx = "2.7.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera-core" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-camera2" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-lifecycle" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-view" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
